version: '3'
services:
	# Nom du conteneur
	mongo-demo-compose:
		image: mongo
		ports:
			- 27018:27017
			# Port changé pour éviter un conflit
		environment:
			- MONGO_INITDB_ROOT_USERNAME=admin
			- MONGO_INITDB_ROOT_PASSWORD=mdp
